<div class="container">
    <div>
        <a href="/"><img src="/image/display/boobs/<?php echo $this->boobsImage ?>" alt="Boobs" /></a>
    </div>
        and
    <div>
        <a href="/"><img src="/image/display/kittens/<?php echo $this->kittensImage ?>" alt="Kittens" /></a>
    </div>

<p>
    <div>
        <a href="http://blog.shupp.org/2010/02/10/mogilefs-zend-framework-boobs-and-kittens/" alt="About This Site">about</a>  &nbsp | &nbsp
        <a href="/index/permalink/images/<?php echo $this->boobsImage . '_' . $this->kittensImage ?>" alt="Link to this pair of images">link to this pair</a>
    </div>
</p>
</div>
