<div class="container">
    <div>
        <a href="/"><img src="/image/display/boobs/<?php echo $this->boobsImage ?>" alt="Boobs" /></a>
    </div>
        and
    <div>
        <a href="/"><img src="/image/display/kittens/<?php echo $this->kittensImage ?>" alt="Kittens" /></a>
    </div>

    <br />

    <div>
        <a href="http://blog.shupp.org/2010/02/10/mogilefs-zend-framework-boobs-and-kittens/" alt="About This Site">about</a>  &nbsp | &nbsp
        <a href="/index/permalink/images/<?php echo $this->boobsImage . '_' . $this->kittensImage ?>" alt="Link to this pair of images">link to this pair</a>
    </div>

    <br />

<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fboobsandkittens.com&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
</div>
