<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="keywords" content="Boobs, Kittens" />
	<meta name="description" content="Boobs and Kittends" />
	<meta name="author" content="Bill Shupp" />
  	<meta name="copyright" content="&copy; 2010 Bill Shupp" />
	<meta http-equiv="imagetoolbar" content="no" />
    <link rel="stylesheet" type="text/css" href="/global.css" media="all" />

	<title>Boobs and Kittens</title>
</head>

<body>

<?php echo $this->layout()->content ?>

</body>
</html>
