<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="keywords" content="Boobs, Kittens" />
	<meta name="description" content="Boobs and Kittends" />
	<meta name="author" content="Bill Shupp" />
  	<meta name="copyright" content="&copy; 2010 Bill Shupp" />
	<meta http-equiv="imagetoolbar" content="no" />
    <link rel="stylesheet" type="text/css" href="/global.css" media="all" />

	<title>Boobs and Kittens</title>
</head>

<body>

<?php echo $this->layout()->content ?>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-4871726-3");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
